// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2yJpox_i8FRjZ6ew_3NDav9UkkXRaGFs',
    appId: '1:174743616791:web:2263cfd5a52da983d90b52',
    messagingSenderId: '174743616791',
    projectId: 'crossword-agent-8fad1',
    authDomain: 'crossword-agent-8fad1.firebaseapp.com',
    storageBucket: 'crossword-agent-8fad1.firebasestorage.app',
    measurementId: 'G-NB9ML5XNF2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtDhXmfUgky83z-FH3BN8vLBrqLjgmcr4',
    appId: '1:174743616791:ios:0f3beb66e76e587bd90b52',
    messagingSenderId: '174743616791',
    projectId: 'crossword-agent-8fad1',
    storageBucket: 'crossword-agent-8fad1.firebasestorage.app',
    iosBundleId: 'com.example.a2uiExplorer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2yJpox_i8FRjZ6ew_3NDav9UkkXRaGFs',
    appId: '1:174743616791:web:93f9c4d958afb70dd90b52',
    messagingSenderId: '174743616791',
    projectId: 'crossword-agent-8fad1',
    authDomain: 'crossword-agent-8fad1.firebaseapp.com',
    storageBucket: 'crossword-agent-8fad1.firebasestorage.app',
    measurementId: 'G-QG402NWGZZ',
  );

}